################################################################################
# JettraStore Core Engine Configuration (database.properties)
# Low-level JVM tuning, Panama FFM settings, JettraPolice, and Storage Paths
################################################################################

# Ubicaci\u00c3\u00b3n expl\u00c3\u00adcita del path del directorio de la base de datos en disco f\u00c3\u00adsico
#jettra.storage.path = /var/jettra/data
jettra.storage.path = /jettra/data

# Estructura LSM y Memoria Off-Heap con Project Panama
jettra.storage.memtable.size.mb = 128
jettra.storage.ram.global.limit.mb = 2048
jettra.storage.offheap.direct = true
jettra.storage.file.extension = .jettra

# Umbrales para la Transici\u00c3\u00b3n Din\u00c3\u00a1mica a Motor de Anillo Distribuido
# Cuando la RAM ocupada alcanza el 85%, el nodo principal descarga carga a los secundarios
jettra.ring.saturation.threshold.percent = 85
jettra.ring.release.target.percent = 45

# Componente Aut\u00c3\u00b3nomo de Supervisi\u00c3\u00b3n Preventiva (JettraPolice)
# Habilitado por defecto en hilo demonio de bajo consumo
jettrapolice.active = true
jettrapolice.interval.ms = 500
jettrapolice.ram.warning.threshold = 75
jettrapolice.disk.warning.threshold = 90

# M\u00c3\u00a9tricas de Rendimiento y Microbenchmarking con JMH
# true para habilitar en pruebas/diagn\u00c3\u00b3stico, false para producci\u00c3\u00b3n de m\u00c3\u00a1xima velocidad
jmh.metrics.active = false

# Seguridad y Autenticaci\u00c3\u00b3n Criptogr\u00c3\u00a1fica con JettraJWT
jettra.security.jwt.algorithm = Ed25519
jettra.security.jwt.expiration.seconds = 86400
jettra.security.jwt.issuer = jettra-store-authority

# Superusuario por Defecto (Provisionamiento Obligatorio Inicial)
# Credenciales: admin / admin-jettra (M\u00c3\u00a1xima prioridad y privilegios absolutos inmutables)
jettra.security.default.admin.username = admin
jettra.security.default.admin.password = admin-jettra

# Red y Puertos de Escucha
jettra.network.grpc.port = 9091
jettra.network.rest.port = 8080
jettra.network.virtualthreads.enabled = true
