# JettraStore Shell Saved Connections for Docker Cluster
cluster_master=jettra-node-01:9091:admin
cluster_node_02=jettra-node-02:9091:admin
cluster_node_03=jettra-node-03:9091:admin
local_master=127.0.0.1:9091:admin
